FROM ruby:3.2.3-bookworm

ARG BUNDLER_VERSION=2.5.23

RUN gem install bundler --version "${BUNDLER_VERSION}" --no-document

WORKDIR /site

COPY Gemfile Gemfile.lock ./
RUN bundle config set path /usr/local/bundle \
    && bundle install --jobs 4 --retry 3

EXPOSE 4000

CMD ["bundle", "exec", "jekyll", "serve", "--host", "0.0.0.0", "--port", "4000", "--no-watch"]
